version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 18
    commands:
      - echo  "installing dependencies ......."
      - npm ci --legacy-peer-deps

  build: 
    commands:
      - echo "building the application ......."
      - npm run build

artifacts:
  files:
  - '**/*'
  base-directory: dist
  discard-paths: no 
  
